name: Example workflow

on:
  workflow_dispatch:
    inputs:
      GH_ENVIRONMENT:
        description: Environment
        type: choice
        options:
          - sandbox
        default: sandbox
      TERRAFORM_ACTION:
        description: Terraform action
        type: choice
        options:
          - apply
          - destroy
        default: apply

jobs:
  # All the development work
  ci:
   name: CI
   runs-on: ubuntu-latest
   steps:
     - run: echo Placeholder for CI stuff
  
  # MAKE SURE YOU CHANGE THE PATH!
  infra:
    name: Infra
    needs: ci
    # CHANGE THIS PATH!
    uses: iveylabs/JM-TF-Modules/.github/workflows/infra-template.yml@main
    with:
      GH_ENVIRONMENT: ${{ github.event.inputs.GH_ENVIRONMENT }}
      TERRAFORM_ACTION: ${{ github.event.inputs.TERRAFORM_ACTION }}
      APP_NAME: "bluehydrogenabacus"
      APP_PROJECT: "DSOPS"
      APP_LOCATION: "northeurope"
      APP_REGION_SHORT: "EU"
      APP_SUFFIX: "001"
      TAG_COUNTRY: "UK"
      TAG_ENVIRONMENT: "SBX-DSOPS-EMEA"
      TAG_MAINT_WINDOW: "NOT REQUIRED"
      TAG_SECTOR: "NONE"
      TAG_COST_CENTER: "012345"
      TAG_APP_OWNER: "paul ivey"
      TAG_CLASSIFICATION: "internal"
      TAG_SERVICE_CLASS: "platinum"
    secrets:
      POLICY_ASSIGNMENT_NAME: ${{ secrets.POLICY_ASSIGNMENT_NAME }}
      POLICY_DEFINITION_ID: ${{ secrets.POLICY_DEFINITION_ID }}
      APP_ENVIRONMENT: ${{ secrets.APP_ENVIRONMENT }}
      OWNER_OBJECT_ID: ${{ secrets.OWNER_OBJECT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      AZURE_CREDS: ${{ secrets.AZURE_CREDS }}
      GH_PAT: ${{ secrets.GH_PAT }}

# Deployment work
