name: Extract object id

on:
  workflow_dispatch:
  
jobs:
  get-id:
    environment: SBX
    name: Get object ID
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDS }}
          enable-AzPSSession: true
          
      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          # Specify the script here
          inlineScript:  az ad user show --id AdeleV@iveymsft.onmicrosoft.com --query objectId -o tsv
