name: Extract object id

on:
  workflow_dispatch:
    inputs:
      login:
        type: text
        description: Login email
  
jobs:
  get-id:
    environment: SBX
    name: Get object ID
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDS }}
          enable-AzPSSession: true
          
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          # Specify the Az PowerShell script here.
          inlineScript: (Get-AzADUser -UserPrincipalName ${{ github.event.inputs.login }}).Id
          azPSVersion: latest
          
      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          # Specify the script here
          inlineScript:  az ad user show --id ${{ github.event.inputs.login }}) --query objectId -o tsv
