name: Test IaC

on:
  workflow_dispatch:
    inputs:
      gh-env:
        type: choice
        options:
          - sandbox
        description: Which GitHub environment
        default: sandbox
      action:
        type: choice
        options:
          - Apply
          - Destroy
        description: Apply or destroy?
        default: Apply

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  APP_NAME: "BLUEHYDROGENABACUS"
  ENVIRONMENT: "SBX"
  PROJECT: "DSOPS"
  REGION_SHORT: "EU"
  APP_SUFFIX: "001"

jobs:
# Create all base resources
  base-infra:
   name: ${{  github.event.inputs.action }} base infra
   runs-on: ubuntu-latest
   environment: ${{ github.event.inputs.gh-env }}
   concurrency:
    group: ${{ github.event.inputs.gh-env }}
    cancel-in-progress: false
   defaults:
     run:
       working-directory: terraform/base
   
   steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_wrapper: false

    - name: Git setup
      run: |
        git config --local --remove-section http."https://github.com/"
        git config --global url."https://foo:${{ env.GH_TOKEN }}@github.com/iveylabs".insteadOf "https://github.com/iveylabs"
      env:
        GH_TOKEN: ${{ secrets.PAT_PUBLIC_REPO }}

    - name: Terraform init
      run: terraform init

    - name: Terraform plan
      run: terraform plan -out="tfplan.bin" -var-file="${{ github.event.inputs.gh-env }}.tfvars" -input=false

    # Apply if that was the selected option
    - name: Terraform apply
      run: terraform apply -input=false -auto-approve "tfplan.bin"
      if: ${{ github.event.inputs.action == 'Apply' }}
      
    # Destroy if that was the selected option
    - name: Terraform destroy
      run: terraform destroy -input=false -auto-approve -var-file="${{ github.event.inputs.gh-env }}.tfvars"
      if: ${{ github.event.inputs.action == 'Destroy' }}

# Exclude from subscription/management group tagging policy
  policy-exclude:
    name: Azure policy exclusion
    needs: base-infra
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.inputs.gh-env }}
      cancel-in-progress: false
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.3
        if: ${{ github.event.inputs.action == 'Apply' }}
        with:
          creds: ${{ secrets.AZURE_CREDS }}
          enable-AzPSSession: true

      - name: Exclude RG from sub tagging policy
        uses: Azure/powershell@v1
        if: ${{ github.event.inputs.action == 'Apply' }}
        with:
          inlineScript: |
            # Get current notScopes list
            $currentNotScopes = (Get-AzPolicyAssignment -Name "${{ secrets.AZ_POLICY_ASSIGNMENT_NAME }}").Properties.NotScopes
            # Add new RG to NotScopes of assignment
            $newNotScopes = $currentNotScopes + "/subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/RG-${{ env.ENVIRONMENT }}-${{ env.PROJECT }}-${{ env.REGION_SHORT }}-${{ env.APP_NAME }}-${{ env.APP_SUFFIX }}"
            # Modify assignment with new NotScopes
            Set-AzPolicyAssignment -Name "${{ secrets.AZ_POLICY_ASSIGNMENT_NAME }}" -NotScope $newNotScopes
          azPSVersion: latest

# Create resource group level tagging policy
  rg-policy:
   name: ${{  github.event.inputs.action }} RG policy assignment
   runs-on: ubuntu-latest
   needs: policy-exclude
   environment: ${{ github.event.inputs.gh-env }}
   concurrency:
    group: ${{ github.event.inputs.gh-env }}
    cancel-in-progress: false
   defaults:
     run:
       working-directory: terraform/policy
   
   steps:    
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_wrapper: false

    - name: Git setup
      run: |
        git config --local --remove-section http."https://github.com/"
        git config --global url."https://foo:${{ env.GH_TOKEN }}@github.com/iveylabs".insteadOf "https://github.com/iveylabs"
      env:
        GH_TOKEN: ${{ secrets.PAT_PUBLIC_REPO }}
        
    - name: Terraform init
      run: terraform init

    - name: Terraform plan
      run: terraform plan -out="tfplan.bin" -var-file="${{ github.event.inputs.gh-env }}.tfvars" -input=false

    # Apply if that was the selected option
    - name: Terraform apply
      run: terraform apply -input=false -auto-approve "tfplan.bin"
      if: ${{ github.event.inputs.action == 'Apply' }}
      
    # Destroy if that was the selected option
    - name: Terraform destroy
      run: terraform destroy -input=false -auto-approve -var-file="${{ github.event.inputs.gh-env }}.tfvars"
      if: ${{ github.event.inputs.action == 'Destroy' }}
